# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d771c27b2a55b7af667755a49d8231851f7c8df3dfd8f62bf09770984c57eef83659a17afcb3ca66880748c42dea2adfce22100d4613c522a44d8c63e4787e92

test:
  secret_key_base: 2e4ba664be46f662f21c75d0b3262fd741ae4b0a3025729e62553ee6f8f2bdb280b697eb33939cfac1cb604e67024410d2398d8d210aa72209c582af7e353977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
